[supervisord]
nodaemon=true

[program:jmusicbot]
command=java -Djava.awt.headless=true -jar /opt/jmusicbot/app.jar
autostart=true
autorestart=true
stderr_logfile=/var/log/java_app.err.log
stdout_logfile=/var/log/java_app.out.log
